[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  directory = "dist_be"
  included_files = ["dist_be/**"]
  node_bundler = "esbuild"

[functions.my-function]
  max_duration = 10

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
